version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Project_HNClone/Project_HNClone.csproj
      - dotnet restore HNCloneApi/HNCloneApi.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output Project_HNClone/Project_HNClone.csproj
      - dotnet publish -c release -o ./build_output HNCloneApi/HNCloneApi.csproj
artifacts:
  files:
    - Project_HNClone/build_output/**/*
    - scripts/**/*
    - appspec.yml
